[package]
name = "c-1-3-hello-cargo"
version = "0.1.0"
authors = ["Jake Carrington <jake.carrington@ditto.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
